name: Run Python

on: [push]

jobs:
  build: 
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      # - uses: webfactory/ssh-agent@v0.7.0
      #   with:
      #     ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install requests
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run Python script
        shell: pwsh
        run: echo 'yes' | python src/main.py 

      - name: Run check folder
        run: | 
          ls
 
      - name: Add new Git remote
        run: |
         git remote add new-origin git@github.com:netchanokmu/workflow.git
     
  
      - name: git Add
        run: |
          git config --global user.email "pimnetcha97@gmail.com"
          git config --global user.name "netchanokmu"
          git add src
     
      - name: git commit
        run: |
          git commit -m "update state"
 
      - name: Push changes to new remote
        run: |
          git push new-origin master  