name: Python Script for Migrate 1
 on:
  workflow_dispatch:
    inputs:
      name:
        description: "Who to greet"
        default: "World1"


 jobs:
   build:
     runs-on: ubuntu-latest

     env:
       FILE_PATH: 'src/organizations_edit.json'
       CLONE_DIRECTORY: 'demo_migrate'
       SELECT_ORGANIZATIONS: 'dataxtest'
       IGNORE_REPOS: ''
       ORG_NAME_MIGRATE: ${{secrets.ORG_NAME_MIGRATE}}
       USERNAME: 'netchanokmu'
       OLD_TOKEN: ${{ secrets.OLD_TOKEN }}
       NEW_TOKEN: ${{secrets.NEW_TOKEN}}


     steps:
     - name: Checkout code
       uses: actions/checkout@v2

     - name: Set up Python
       uses: actions/setup-python@v2
       with:
         python-version: 3.8  # You can change this to your desired Python version
     - uses: webfactory/ssh-agent@v0.7.0
       with:
         ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
  
     - name: Install dependencies (if needed)
       run: |
         pip install requests  # Install the 'requests' module

       continue-on-error: true

     - name: Run Python script
       shell: pwsh
       run: echo 'yes' | python src/main.py # Replace with the actual name of your Python script

     - name: Run check folder
       run: | 
         ls

     - name: Add new Git remote
       run: |
        git remote add new-origin git@github.com:netchanokmu/workflow.git
    
 
     - name: git Add
       run: |
         git config --global user.email "pimnetcha97@gmail.com"
         git config --global user.name "netchanokmu"
         git add src
    
     - name: git commit
       run: |
         git commit -m "update state"

     - name: Push changes to new remote
       run: |
         git push new-origin master  
